### ISSUE TITLE
Support tracing in ClojureScript

### ISSUE THREAD

**Issue by WilliamParker** [cerner/clara-rules#308]
Similarly to https://github.com/cerner/clara-rules/issues/307 I don't see a reason why [tracing](https://github.com/cerner/clara-rules/blob/0.15.0/src/main/clojure/clara/tools/tracing.clj) needs to be Clojure-only.  This is mostly, at least in the usage I'm aware of, a low-level  tool for debugging and diagnosing performance problems, so it is probably a lower priority than https://github.com/cerner/clara-rules/issues/307, and for my part I'm more likely to work on https://github.com/cerner/clara-rules/issues/307 since I have more use for that.  If anyone has need of session tracing in ClojureScript a PR would be welcome though.

**Comment by alex-dixon** [comment]
Precept has [`listeners`](https://github.com/CoNarrative/precept/blob/master/src/clj/precept/listeners.cljc) which is copied from Clara's `tracing`. It's a CLJC file and is used successfully in CLJS. 

I just tried converting `tracing` to `.cljc` and it broke [this test](https://github.com/alex-dixon/clara-rules/blob/master/src/test/clojure/clara/tools/test_inspect.clj#L182). Interestingly, `_ (println bindings matches)` on line 180 fixed it for me but I wasn't able to find a real solution.

We may not be able to directly port existing CLJ tests for tracing to CLJC because they use `dsl/parse-rule` and `dsl/parse-query`, which are CLJ-only.

**Comment by WilliamParker** [comment]
@alex-dixon If you push a branch with the uplift you did I can take a look at why it might have failed.  Regarding the testing, I'd anticipate uplifting the tracing tests to use [def-rules-test](https://github.com/cerner/clara-rules/blob/c67b41bc9ea826030ba612579ef21f490433ccd0/src/main/clojure/clara/tools/testing_utils.clj#L10) as part of this so that they can be shared between Clojure and ClojureScript, similar to the uplift to test-accumulators in https://github.com/cerner/clara-rules/pull/312.  def-rules-test was added for issue https://github.com/cerner/clara-rules/issues/296 and there is discussion of it there.

**Comment by alex-dixon** [comment]
@WilliamParker Thanks. Will do. I actually noticed in the PR I have open that tests were failing locally before I made any changes. Will check again. Thanks for the tip with `def-rules-test`.

**Comment by WilliamParker** [comment]
I merged the PR.  Would it be helpful to have a release with this and [the schema upgrade](https://github.com/cerner/clara-rules/commit/c5c060390b4fba8671f847d9eedcb43287ea004f) in it?  I'm traveling right now but I can plan on cutting a release sometime next week or the week after that when I'm back unless someone else gets to it first.  I think the appropriate versioning for such a release would be 0.15.1 but we can discuss if anyone disagrees; it isn't something I feel strongly about.

**Comment by rbrush** [comment]
Agreed that 0.15.1 makes sense. I'm happy to do the release since Will is traveling right now.

**Comment by alex-dixon** [comment]
Ready any time. No rush or hurry. Thank you :)

**Comment by rbrush** [comment]
Closing this since @WilliamParker had merged the PR and preparing to include in 0.15.1.
