### ISSUE TITLE
Provide mechanism for annotating session context, and retrieving said context

### ISSUE THREAD

**Issue by dcj** [cerner/clara-rules#31]
From a brief conversation & email thread with @rbrush at @clojure_conj

I'd like to be able to provide some arbitrary context to a Clara session I create.
Perhaps by adding a keyword/map to mk-session, and anything I put into the map is stored in the session.

Later, when a rule fires, I would like to be able to get this context, as well as other particulars from Clara as to why that rule fired, etc.

My intention is to use this for logging, and perhaps to persist "derived" facts to a (persistent) event store.

**Comment by WilliamParker** [comment]
Regarding the initial question, perhaps we could simply add support for Clojure metadata to sessions.  i.e.

````
(with-meta (-> mk-session [your-rule]) whatever-meta-you-want))
````

This seems like it would meet the initial need logged here and fits in with the overall Clojure ecosystem.  Otherwise, this issue seems to have several different discussions, and as @rbrush suggests the mailing list is probably a better place for some of them.  My initial inclination is to log an enhancement to add metadata support to sessions, close this issue, and log new issues/discuss on the mailing list if anyone wants to discuss any of these topics further.

Thoughts?

**Comment by rbrush** [comment]
I don't object to adding metadata to sessions, if there is a need. 

I'm not sure there is really a need, but metadata support doesn't really complicate the API, so I'm fine with it if it's useful for someone. If so, +1 to @WilliamParker's suggestion of logging a separate issue for that and closing this one.

**Comment by WilliamParker** [comment]
This hasn't had any activity other than my proposal to add Clojure metadata to satisfy the original need in several years.  That proposal was made several months ago and nobody has spoken up to say that they would find it useful.  At this point I think this issue is just a distraction in the issues list and will close it accordingly.

If anyone wants to revisit metadata support or one of the other subjects discussed in the thread, please log a new issue or post on the Google Groups mailing list as appropriate for the topic in question.
