### ISSUE TITLE
Inconsistent naming on Fact Type Customization example

### ISSUE THREAD

**Issue by felipe-campos** [cerner/clara-rules#333]
The last example given at [Fact Type Customization](http://www.clara-rules.org/docs/fact_type_customization/) is a bit confusing because of that.

At the last paragraph: 

> Clara will then call the ancestors-fn with an argument of :precise-temperature-fn.

should be

Clara will then call the ancestors-fn with an argument of **:precise-temperature-reading**.

, and

> In this case, since :temperature-reading is in the set of ancestors of :precise-temperatures-fn it is considered…

should be

In this case, since :temperature-reading is in the set of ancestors of **:precise-temperatures-reading** it is considered…

**Comment by WilliamParker** [comment]
@felipe-campos Thanks for pointing that out.  I pushed https://github.com/cerner/clara-site/commit/36e8fd926f9602c20733446ddac1b6eed76a69ec to fix this.

I'm going to go ahead and close this since the change seems straightforward, but feel free to reopen if I made a mistake in the fix or there is more to discuss about it.
