### ISSUE TITLE
Inconsistent behavior when using the 'all' accumulator

### ISSUE THREAD

**Issue by EthanEChristian** [cerner/clara-rules#338]
The [all](https://github.com/cerner/clara-rules/blob/master/src/main/clojure/clara/rules/accumulators.cljc#L186) accumulator has an initial value of vector and values are accumulated into this vector. 

However if there is a retraction, due to [drop-one-of](https://github.com/cerner/clara-rules/blob/master/src/main/clojure/clara/rules/accumulators.cljc#L38) the vector will become a sequence. 

I am not sure this would classify as defect, however it does make me wonder if this accumulator should be consistent with and without retractions.

Clojure Version: 1.8
Clara Version: 0.15.2

**Comment by mrrodriguez** [comment]
I thought that this was fixed long ago, but I think I just did that in a branch at some point.

There is already a fn very similar to `clara.rules.accumulators/drop-one-of`, which is `clara.rules.memory/remove-first-of-each`. It has the added benefit being a bit more optimized. Maybe that should be moved to some common location and used instead? It doesn't take the same signature as `c.r.a/drop-one-of`, but it could be used. Or we could duplicate this sort of logic, I'm just pointing it out due to the similarity in the "remove one" match part of the logic.

I agree with this issue though that `c.r.a/all` has odd `:retract-fn` behavior. It is nearly "incorrect" in that an insertion, retraction, then insertion of the same fact against the accumulator would result in different ordering if the first insertion was done against a vector (append as last item) and the second insertion was done against a generic seq/list (append as first item).

**Comment by EthanEChristian** [comment]
As it seems that `remove-first-of-each` has a bit more overhead, could we go with something like:

```
(defn- drop-one-of
  [^PersistentVector items value]
  (let [idx (.indexOf items value)]
    (if (> idx -1)
      (into (subvec items 0 idx) (subvec items (inc idx)))
      items)))
```
The `if` is probably unnecessary considering the usage would be retracting an item from an accumulator where it should be present.

thoughts @mrrodriguez @WilliamParker ?

**Comment by mrrodriguez** [comment]
`subvec` is really efficient in time, but it retains all the original vector's memory. That is why we typically can't really use it for efficient splicing of items out of vector.

There are actually persistent data libs out there that do allow this sort of behavior, but not going to bring in more dependencies here.

More streamlined behavior for the `all` accumulator may actually be to hold off on retractions until `:convert-return-fn` to hope to minimize the amount of rebuilding of the structure. However, that is a bigger change to consider. Another possibility would be to use mutable state throughout the `:reduce-fn` lifecycle. I don't think we've done much with mutable state there before. I'd think that that should be semantically fine, but perhaps there are edge cases.

Most straight forward way to do this change is to just do a `loop` + `recur` sort of structure or `reduce` that just rebuilt the vector from scratch, but skipped the single occurrence of the item it was looking for.

I'm sure Will will have thoughts.

**Comment by WilliamParker** [comment]
- Relying on the ordering of elements being passed into an accumulator seems dangerous in most cases, although if one were very careful it could be deterministically controlled by salience.  In general in Clojure things mostly just operate on the seq abstractions, which we're conforming to still, so I don't really see this as a bug.  Nevertheless, I can see some benefit to being consistent in the type we return, and since the "main" path without retraction is a vector it probably makes sense to go with returning a vector as the way forward, rather than always returning a list, for the sake of passivity.
- Agreed that subvec isn't the way to go here since it will effectively create a memory leak by holding onto the vector from which it is derived.  See the [SubVector constructor](https://github.com/clojure/clojure/blob/clojure-1.8.0/src/jvm/clojure/lang/APersistentVector.java#L549) which is called by the [subvec function](https://github.com/clojure/clojure/blob/964232c7bf442787740fa0200b289b3495b1ec09/src/clj/clojure/core.clj#L3772) via [the subvec method in clojure.lang.RT](https://github.com/clojure/clojure/blob/964232c7bf442787740fa0200b289b3495b1ec09/src/jvm/clojure/lang/RT.java#L1586).
- Using a stateful construct here would not be safe.  Suppose that you did something like:

````
(def session (mk-session [rule-using-accumulate-all-on-AFact]))
(def with-a-fact (insert session (->AFact)))
(def with-another-fact (insert with-a-fact (->AFact)))
````

If the underlying collection produced by the accumulation were mutable, you could end up sharing a single mutable structure between the sessions with-a-fact and with-another-fact to represent the result of the accumulation in both.  This isn't correct since they have different numbers of AFact facts.  The [memory's to-persistent implementation](https://github.com/cerner/clara-rules/blob/0.15.2/src/main/clojure/clara/rules/memory.cljc#L899) won't try to make the facts themselves persistent, and since they are arbitrary things from the user I don't see that as a good path to try to go down.



Overall I don't see this as something that we need to try to optimize too much until and unless we have evidence that it is actually a problem, especially since in general if performance is a major problem in many cases one probably shouldn't be using the all accumulator.  Perhaps just something like

````
(into []
      cat
      [(take-while pred items)
      (rest (drop-while pred items))])
````

The approach of manually building out the new vector via loop-recur would be somewhat more complex, but not unmanageably so IMO and could also be a reasonable approach.  If we do want to heavily optimize accumulating all facts at some point the most fruitful approach would likely be to use a specialized node for it in the engine, at which point you'd be using the optimizations in the Clara memory.  Taking a step back though, the all accumulator is just a normal accumulator, and so if a user runs into particular problems it would be readily possible to write their own implementation with optimizations as appropriate for their use-case.  For example, a frequencies map could be used to avoid the need for linear scans.

**Comment by mrrodriguez** [comment]
> If the underlying collection produced by the accumulation were mutable, you could end up sharing a single mutable structure between the sessions with-a-fact and with-another-fact to represent the result of the accumulation in both.

I wasn't clear enough. I meant using a mutable structure was completely isolated to the `:reduce-fn`.  The `:initial-value` would be nil. `:reduce-fn` would create the structure when ran if it was not made yet.  The `:convert-return-fn` would change back to something persistent.

I think that should be safe with the semantics at least. I'm not saying I'd jump to trying something like that though unless it had enough benefit to be considered (not likely).

I still do think that putting all rebuilding in the `:convert-return-fn` would likely be the most robust as long as the rest of the engine was operating in effectively large batches. However, again, not really that necessary until proven otherwise. Just tweaking the `:reduce-fn` to build a vector like the transducer approach from Will above seems fine.

**Comment by WilliamParker** [comment]
@mrrodriguez I think the problem with that approach is that the result of the :reduce-fn is added to the memory directly, _without_  first being processed by the :convert-return-fn.  So to clarify, I think you'd have mutable things [added to the accum memory](https://github.com/cerner/clara-rules/blob/0.15.2/src/main/clojure/clara/rules/memory.cljc#L692).  See for example [right-activate in AccumulateNode](https://github.com/cerner/clara-rules/blob/master/src/main/clojure/clara/rules/engine.cljc#L1158) where the converted values are propagated to child nodes but the unconverted reduced values are stored in the memory.  Clara has to do (or accumulate from scratch for every new fact) that since future reduces will be done on the reduced value, not the previous converted value.  So you could end up having two or more sessions both having the same reduced reference to a mutable object in their memory.  Perhaps I'm misunderstanding and you're proposing converting back to a persistent collection at an earlier stage than I'm thinking though.

**Comment by mrrodriguez** [comment]
> Perhaps I'm misunderstanding and you're proposing converting back to a persistent collection at an earlier stage than I'm thinking though.

You're right. I forgot the current impl stored the result of `:reduce-fn` and `:retract-fn` in memory. So bad idea to use stateful objects in these functions.

So the only approach I think may be better than repeated rebuilding of the vector held by `:reduce-fn` would be to hold 2 collections, those accumulated so far, and those retracted so far. Then in the `:convert-return-fn` do a "remove-first-of-each" style operation to build the final collection that "single" time.
I haven't tested out that idea and it is probably more complicated than we really need here, as we've said before. The `into []` transducer idea seemed fine to me.

**Comment by WilliamParker** [comment]
I'm going to close this issue since the PR has been merged.  We can reopen it if others disagree and still see work to do here.
