### ISSUE TITLE
`acc/max` and `acc/min` returning wrong fact

### ISSUE THREAD

**Issue by mauricioszabo** [cerner/clara-rules#405]
When I `insert!` a fact inside a `defrule`, the `acc/max` don't return the "max" fact. I've tested with the following code:

```clojure
(ns events-reports.core
  (:require [clara.rules :refer :all]
            [clara.rules.accumulators :as acc]))

(defrecord Status [id status cid])
(defrecord Event [cid kind])

(defrule new-event
  [Event (= ?cid cid) (= kind "initial")]
  =>
  (insert! (->Status 0 "initial" ?cid)))

(defrule status-change
  [Event (= ?cid cid) (= kind "pay")]
  [?s <- (acc/max :id :returns-fact true) :from [Status (= ?cid cid)]]
  =>
  (insert! (-> ?s (assoc :status "paid") (update :id inc)))
  (println ?s)
  (Thread/sleep 1000)) ; This is here because the process loops forever

(defquery curr-status []
  [?status <- (acc/max :id :returns-fact true) :from [Status]])

(defn run []
 (let [session (-> (mk-session 'events-reports.core)
                   (insert (->Event 1 "initial")
                           (->Event 1 "pay"))
                   (fire-rules))]
   (query session curr-status)))
```

This prints `#events_reports.core.Status{:id 0, :status initial, :cid 1}` forever - notice that I inserted a new fact with id=1, but the accumulator doesn't sees it and just returns the id=0.

**Comment by EthanEChristian** [comment]
@mauricioszabo,
I believe that the issue here is that truth maintenance is occurring.

In the example you have provided in the rule with the join you are binding to 2 facts, an event and the status with the max id with matching `?cid`. When the rule fires and satisfies both conditions it then inserts a new `Status` with a higher `id`. However this makes the initial 2 conditions invalid as the initial status is no longer the max, thus logically retracting the newer Status with the higher id. This in turn means that the initial Status now has the max id and repeat forever.

**Comment by EthanEChristian** [comment]
I'm not 100% sure of your use case here, but perhaps adding a guard in the `max` accumulator to ignore `Statuses` that are paid?

something like:
```
[?s <- (acc/max :id :returns-fact true) :from [Status (= ?cid cid) (not= status "paid")]]
```

**Comment by mauricioszabo** [comment]
Yes, indeed that's the problem. Makes sense.
